# execute unit tests on windows

name: Windows CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    # run on latest windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        make prepare
    # so far, we made env ready
    # 1. configure
    - name: configure
      run: |
        cmake -H"." -Bbuild -T host=x86 -A x64 -DCMAKE_BUILD_TYPE="Debug"
    # 2. build project
    - name: building
      # just execute the unit test
      run: |
        cmake --build build --config Debug --target unit_tests -j4
    # 3. test 
    - name: testing
      run: |
        cd build
        cd tests
        cd Debug
        .\unit_tests.exe